# Docker Image Settings
image:
  repository: 127.0.0.1:5000/gofiber-helloworld
  tag: latest
  pullPolicy: Always

# Kubernetes Service Port
service:
  port: 8080 

probes:
  path: "/api/health"
  initialDelaySeconds: 10

config:
  fileName: "config.yaml"

# Resource Usage
resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

# Autoscaling
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

# Ingress
ingress:
  enabled: true
  main:
    enabled: true
    host: dev.goapp.stagingenvironment.space
  subpath:
    enabled: true
    host: dev.apps.stagingenvironment.space
    path: /goapp
    stripPrefix: true

basicAuth:
  enabled: false
  users: []

# Secrets (Helm chart will convert these to environment variables)
# Put them into github secret manager
secrets:
  DB_PASSWORD: ""
  JWT_SECRET: ""
  API_KEY: ""